import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import { Button } from './Button';
import { Badge } from './Badge';
import { formatPrice, generateWhatsAppLink } from '../../utils';
import { Eye, MessageCircle } from 'lucide-react';
export function ProductCard({ product, onQuickView }) {
    return (_jsxs(motion.div, { className: "bg-white rounded-xl shadow-md overflow-hidden group relative flex flex-col h-full", whileHover: { y: -5 }, transition: { duration: 0.2 }, children: [_jsx(Badge, { badge: product.badge }), _jsxs("div", { className: "aspect-square overflow-hidden relative flex-shrink-0", children: [_jsx("img", { src: product.image, alt: product.name, className: "w-full h-full object-contain transition-transform duration-300 group-hover:scale-105", loading: "lazy", onError: (e) => {
                            const target = e.target;
                            target.src = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHQ9IjQwMCIgaGVpZ2h0PSI0MDAiIHZpZXdCb3g9IjAgMCA0MDAgNDAwIj48cmVjdCB3aWR0aD0iNDAwIiBoZWlnaHQ9IjQwMCIgZmlsbD0iI0Y4QUFGQ2YiIC8+PHJlY3QgeD0iNTAiIHk9IjUwIiB3aWR0aD0iMzAwIiBoZWlnaHQ9IjMwMCIgcng9IjIwIiBmaWxsPSIjRTRFNkVGIi8+PHRleHQgeD0iMjAwIiB5Mj0iMjAwIiBmb250LWZhbWlseT0iSW50ZXIsIHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMjQiIGZpbGw9IiMzMzQxNTUiIHRleHQtYW5jaG9sVHlwZT0ibWlkZGxlIj5QcmljZTwvdGV4dD48dGV4dCB4PSIyMDAiIHkyPSIyNDAiIGZvbnQtZmFtaWx5PSJJbnRlLCBzYW50LXNlcmlmIiBmb250LXNpemU9IjE4IiBmaWxsPSIjMzM0MTU1Ij5QcmljZzwv dGV4dD48L3N2Zz4=';
                        } }), _jsx("div", { className: "absolute inset-0 bg-black bg-opacity-0 group-hover:bg-opacity-10 transition-opacity" })] }), _jsxs("div", { className: "p-4 space-y-3 flex-grow flex flex-col", children: [_jsx("span", { className: "text-xs font-medium text-secondary-emerald uppercase tracking-wider", children: product.category.replace('-', ' ') }), _jsx("h3", { className: "font-heading font-bold text-base sm:text-lg text-primary-navy line-clamp-2 flex-grow", children: product.name }), _jsx("p", { className: "text-sm text-neutral-dark line-clamp-2", children: product.specifications[0] }), _jsxs("div", { className: "space-y-2 pt-2", children: [_jsxs("div", { className: "flex justify-between items-center", children: [_jsx("span", { className: "text-sm text-neutral-dark", children: "Unit Price" }), _jsx("span", { className: "font-bold text-primary-blue text-sm sm:text-base", children: formatPrice(product.unitPrice) })] }), _jsxs("div", { className: "flex justify-between items-center", children: [_jsxs("span", { className: "text-sm text-neutral-dark", children: ["Carton (", product.cartonQuantity, ")"] }), _jsx("span", { className: "font-bold text-secondary-emerald text-sm sm:text-base", children: formatPrice(product.cartonPrice) })] }), product.colors.length > 0 && (_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-sm text-neutral-dark", children: "Colors:" }), _jsxs("div", { className: "flex gap-1", children: [product.colors.slice(0, 3).map((color, i) => (_jsx("span", { className: "text-xs bg-neutral-medium px-2 py-1 rounded", children: color }, i))), product.colors.length > 3 && (_jsxs("span", { className: "text-xs", children: ["+", product.colors.length - 3] }))] })] }))] }), _jsxs("div", { className: "flex flex-col sm:flex-row gap-2 sm:gap-3 pt-3 sm:pt-4 mt-auto", children: [_jsxs(Button, { variant: "outline", size: "sm", onClick: () => onQuickView(product), className: "w-full sm:w-[100px] sm:flex-none min-h-[44px]", children: [_jsx(Eye, { size: 16 }), "Quick View"] }), _jsxs(Button, { variant: "secondary", size: "sm", href: generateWhatsAppLink(product), className: "w-full sm:w-[100px] sm:flex-none min-h-[44px]", children: [_jsx(MessageCircle, { size: 16 }), "WhatsApp"] })] })] })] }));
}
